# Generated by Django 5.2.3 on 2025-09-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
