# Generated by Django 4.2.11 on 2026-01-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_review_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
