# Generated by Django 4.2.11 on 2026-01-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_order_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
